### PR TITLE
Exporting pcap_get_selectable_fd as getfd.

### PR DESCRIPTION
**Pull request by geekhckr**

### CODE REVIEW

**Comment by gpotter2** [comment]
Hello @martinuy, could this gets merged ? Would be useful

**Comment by asolino** [comment]
Thanks for the PR @geekhckr and sorry for the delay.

**Comment by gpotter2** [comment]
Thanks a lot @asolino, would it be possible to release a new version of pcapy 0.11.2 ? Would be great for us ! Thanks !!!

**Comment by gpotter2** [comment]
@asolino @martinuy Hello, sorry for pinging back, could it be possible to have a release containing this fix ? It really would help us a lot. Thanks !

**Comment by asolino** [comment]
Hey @gpotter2 

Merging it now, thanks! I will tag a release soon.

**Comment by gpotter2** [comment]
Thanks !
Does this also works on Unix systems ? Or is Linux only ?

**Comment by asolino** [comment]
https://github.com/CoreSecurity/pcapy/releases/tag/0.11.2

> Does this also works on Unix systems ? Or is Linux only ?

Haven't tested it on other Unix systems. Testing welcomed :)

**Comment by guedou** [comment]
Thanks for the release. Could you push 0.11.2 to pipy ? Thanks!

**Comment by asolino** [comment]
I just did @guedou.

**Comment by guedou** [comment]
Thanks ! I just sent a PR to Scapy https://github.com/secdev/scapy/pull/1315

**Pull request merged**
