### PR TITLE
Add setdirection method

### PR DESCRIPTION
**Pull request by dajose**
Add support for libpcap set_direction method, see  #59

### CODE REVIEW

**Comment by dajose** [comment]
@asolino what do you think of this proposal?

**Comment by asolino** [comment]
Hey @dajose 

Thanks for the PR! it actually looks good and I think it'll fit well (although haven't run the testcases). I won't be merging this one tho since this project has been transferred to the HelpSystems organization (that I'm not part of). You will be reached out by the new maintainers soon.

**Comment by dajose** [comment]
@asolino someone I can poke?

**Comment by asolino** [comment]
I'm not sure @dajose  . Try emailing oss @ coresecurity.com. HelpSystems owns CoreSecurity now.

**Comment by dajose** [comment]
sure, thanks @asolino  :)

**Comment by gpotter2** [comment]
Let's just hope it actually is transferred to someone :/

Good luck for your next projects asolino, and thanks for the support you provided here :smile:

**Comment by BobbyAtCore** [comment]
Hi @dajose, I'm one of @asolino's former coworkers who's still on the Core Security side and I'll be taking over the maintenance of pcapy. As soon as we get the permissions sorted out, I'll be getting this PR merged in.

**Comment by dajose** [comment]
thanks @BobbyAtCore  :) :) :)

**Review by BobbyAtCore — APPROVED** [review]

**Comment by BobbyAtCore** [comment]
Give me a day or so. I just noticed that everything from GitHub was being eaten by our spamfilter @carlos-jenkins.

**Comment by gpotter2** [comment]
@carlos-jenkins I'd advise you to get a version that doesn't contain https://github.com/helpsystems/pcapy/pull/61#discussion_r303852278 😄 
This project is dead, and now dangerously broken. (if that answers https://github.com/secdev/scapy/pull/2057#issuecomment-507502842 😉)

**Pull request merged**
