### PR TITLE
Move from distutils to setuptools to allow for egg building

### PR DESCRIPTION
**Pull request by Yasumoto**

### CODE REVIEW

**Comment by Yasumoto** [comment]
ping

**Comment by rgs1** [comment]
ping @core-ablanco

**Comment by core-ablanco** [comment]
Sorry for the delay.
Can someone explain me what are the advantages of using setuptools instead of distutils?

**Comment by Yasumoto** [comment]
No worries, thanks for getting back to us!

The [Python Packaging website itself](https://packaging.python.org/en/latest/current.html?highlight=distutils#id13) is probably the best (and canonical) source of the information- for the most part the PyPA is moving people toward setuptools as the supported mechanism for packaging.

**Pull request merged**
