### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by gpotter2**
- Updates documentation with all recent changes (getfd, monitor, missing...)
- fixes https://github.com/CoreSecurity/pcapy/issues/42

### CODE REVIEW

**Comment by gpotter2** [comment]
@martinuy @asolino Hello !
Here is the updated documentation, with all recent changes that had not been documented.

After merging this PR, please release a new version ! It would really help us

**Comment by martinuy** [comment]
@gpotter2 : nice, thanks!

**Comment by gpotter2** [comment]
Hi @martinuy, could we have a new release supporting those new functions please ?
It would allow us to actually use this work. Thanks !

**Comment by martinuy** [comment]
Hi @gpotter2 , sorry for the delay. It makes sense to release a new minor version. I'm trying to coordinate that as I'm not currently managing releases -only code reviews-.

**Comment by asolino** [comment]
Hey folks, just tagged [0.11.4](https://github.com/CoreSecurity/pcapy/tree/0.11.4) and uploaded it to [pypi](https://pypi.org/project/pcapy/0.11.4/).

Thanks for your help and contributions.

**Pull request merged**
